name: CompatHelper
on:
  schedule:
    - cron: '00 00 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, reopened]

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.GHACTION_PRIV }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
